// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-contrast/CharcoalLift.tsx": () => import("../components/mockups/hero-contrast/CharcoalLift.tsx"),
  "./components/mockups/hero-contrast/DarkPremium.tsx": () => import("../components/mockups/hero-contrast/DarkPremium.tsx"),
  "./components/mockups/hero-contrast/WarmEmber.tsx": () => import("../components/mockups/hero-contrast/WarmEmber.tsx")
};
